version: '3'

services:
  celery_worker:
    build: .
    command: celery -A src.celery_config:celery worker -l info --pool=prefork --max-memory-per-child=600000
    env_file:
      - ./.env
    deploy:
      resources:
        limits:
          memory: 1.4G
    volumes:
      - /tmp:/temp_file_storage
        
  celery_beat:
    build: .
    command: celery -A src.celery_config:celery beat -l info
    env_file:
      - ./.env
    deploy:
      resources:
        limits:
          memory: 512M
    volumes:
      - /tmp:/temp_file_storage

networks:
  shared-network:
    name: shared_network
    external: true
