"""Add daily report table

Revision ID: b5ea141598c6
Revises: eb50908b8609
Create Date: 2025-09-03 21:28:14.940124

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b5ea141598c6"
down_revision: Union[str, None] = "eb50908b8609"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "daily_reports",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("daily_report", sa.String(), nullable=True),
        sa.Column("daily_report_type", sa.String(), nullable=True),
        sa.Column("sent_at", sa.DateTime(), nullable=True),
        sa.Column("actionable_email_ids", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("information_email_ids", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("text_report", sa.String(), nullable=True),
        sa.Column("html_report", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_daily_reports_id"), "daily_reports", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_daily_reports_id"), table_name="daily_reports")
    op.drop_table("daily_reports")
    # ### end Alembic commands ###
