"""add is_shown

Revision ID: e331e5c758c2
Revises: 02ec714d22ed
Create Date: 2025-07-29 21:18:26.688331

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e331e5c758c2"
down_revision: Union[str, None] = "02ec714d22ed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("emails", sa.Column("is_shown", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("emails", "is_shown")
    # ### end Alembic commands ###
