"""Add membership status

Revision ID: e3364844936d
Revises: f52915b73bb2
Create Date: 2025-06-12 00:44:16.470613

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e3364844936d"
down_revision: Union[str, None] = "f52915b73bb2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("membership_status", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "membership_status")
    # ### end Alembic commands ###
