"""add is_processed flag

Revision ID: 27349352d157
Revises: d573eaf54158
Create Date: 2025-06-23 20:06:00.529534

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "27349352d157"
down_revision: Union[str, None] = "d573eaf54158"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "call_sessions", sa.Column("is_processed", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("call_sessions", "is_processed")
    # ### end Alembic commands ###
