"""Add call session

Revision ID: d573eaf54158
Revises: e3364844936d
Create Date: 2025-06-19 01:57:15.178940

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d573eaf54158"
down_revision: Union[str, None] = "e3364844936d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "call_sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("follow_up_tasks", sa.ARRAY(sa.JSON()), nullable=True),
        sa.Column("call_control_id", sa.String(), nullable=True),
        sa.Column("recording_url", sa.String(), nullable=True),
        sa.Column("is_completed", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_call_sessions_id"), "call_sessions", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_call_sessions_id"), table_name="call_sessions")
    op.drop_table("call_sessions")
    # ### end Alembic commands ###
