"""remove unique table constraint

Revision ID: eb50908b8609
Revises: f6103654f601
Create Date: 2025-08-26 12:17:59.131751

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "eb50908b8609"
down_revision: Union[str, None] = "f6103654f601"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_email_account_id_email_id", "emails", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "unique_email_account_id_email_id", "emails", ["email_account_id", "email_id"]
    )
    # ### end Alembic commands ###
