"""Add expires_at to tokens

Revision ID: 143c35817687
Revises: 66d7ad7f5412
Create Date: 2025-04-19 13:00:36.922886

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "143c35817687"
down_revision: Union[str, None] = "66d7ad7f5412"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tokens", sa.Column("expires_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tokens", "expires_at")
    # ### end Alembic commands ###
