"""add categories

Revision ID: 298b8a067fb8
Revises: e331e5c758c2
Create Date: 2025-07-31 02:06:00.853725

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "298b8a067fb8"
down_revision: Union[str, None] = "e331e5c758c2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "emails", sa.Column("categories", postgresql.ARRAY(sa.String()), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("emails", "categories")
    # ### end Alembic commands ###
