"""Add email folder

Revision ID: 5771cb3cc1dd
Revises: a1ff6f0c9623
Create Date: 2025-04-25 18:56:15.086540

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5771cb3cc1dd"
down_revision: Union[str, None] = "a1ff6f0c9623"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "emails",
        sa.Column("folder", sa.String(), server_default="inbox", nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("emails", "folder")
    # ### end Alembic commands ###
