"""Create weekly_email_recaps with categories

Revision ID: d7f9f7862638
Revises: 9dc61e71333c
Create Date: 2025-08-11 20:25:09.644870

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d7f9f7862638"
down_revision: Union[str, None] = "9dc61e71333c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "weekly_email_recaps",
        sa.Column("categories", postgresql.ARRAY(sa.String()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("weekly_email_recaps", "categories")
    # ### end Alembic commands ###
