"""Add email attachment

Revision ID: 9e43472af06c
Revises: d1c0c7fd0baa
Create Date: 2025-06-06 20:59:01.595396

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9e43472af06c"
down_revision: Union[str, None] = "d1c0c7fd0baa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_attachments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email_id", sa.UUID(), nullable=True),
        sa.Column("attachment_id", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("content_type", sa.String(), nullable=True),
        sa.Column("size", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("processed", sa.Boolean(), nullable=True),
        sa.Column("uploaded", sa.Boolean(), nullable=True),
        sa.Column("filepath", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["email_id"],
            ["emails.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_email_attachments_id"), "email_attachments", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_email_attachments_id"), table_name="email_attachments")
    op.drop_table("email_attachments")
    # ### end Alembic commands ###
