"""Add WeeklyEmailRecap table and relationship

Revision ID: b081354b2a73
Revises: 2b2dbfb43e29
Create Date: 2025-08-12 20:58:57.646082

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b081354b2a73"
down_revision: Union[str, None] = "2b2dbfb43e29"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
