"""add is_read flag

Revision ID: a1ff6f0c9623
Revises: 143c35817687
Create Date: 2025-04-22 11:19:32.114715

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a1ff6f0c9623"
down_revision: Union[str, None] = "143c35817687"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("emails", sa.Column("is_read", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("emails", "is_read")
    # ### end Alembic commands ###
