"""Add WeeklyEmailRecap table and relationship

Revision ID: 2b2dbfb43e29
Revises: d7f9f7862638
Create Date: 2025-08-12 20:57:27.798524

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2b2dbfb43e29"
down_revision: Union[str, None] = "d7f9f7862638"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
