"""add weekly_email_recap table

Revision ID: 96c1eddfddac
Revises: ad6c781d69e9
Create Date: 2025-08-11 19:43:19.491767

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "96c1eddfddac"
down_revision: Union[str, None] = "ad6c781d69e9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "weekly_email_recaps",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("week_start", sa.DateTime(), nullable=False),
        sa.Column("week_end", sa.DateTime(), nullable=False),
        sa.Column("summary", sa.UnicodeText(), nullable=True),
        sa.Column("email_ids", postgresql.ARRAY(sa.UUID()), nullable=True),
        sa.Column("email_account_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["email_account_id"],
            ["email_accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_weekly_email_recaps_id"), "weekly_email_recaps", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_weekly_email_recaps_id"), table_name="weekly_email_recaps")
    op.drop_table("weekly_email_recaps")
    # ### end Alembic commands ###
