"""Create weekly_email_recaps with email_id

Revision ID: 9dc61e71333c
Revises: 8ce6bddcd6fe
Create Date: 2025-08-11 20:23:39.871453

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9dc61e71333c"
down_revision: Union[str, None] = "8ce6bddcd6fe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "weekly_email_recaps",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("week_start", sa.DateTime(), nullable=False),
        sa.Column("week_end", sa.DateTime(), nullable=False),
        sa.Column("summary", sa.UnicodeText(), nullable=True),
        sa.Column("email_account_id", sa.UUID(), nullable=False),
        sa.Column("email_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["email_account_id"],
            ["email_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["email_id"],
            ["emails.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_weekly_email_recaps_id"), "weekly_email_recaps", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_weekly_email_recaps_id"), table_name="weekly_email_recaps")
    op.drop_table("weekly_email_recaps")
    # ### end Alembic commands ###
