"""add outlook

Revision ID: 66d7ad7f5412
Revises: 8940cfdef107
Create Date: 2025-04-18 15:46:16.807064

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "66d7ad7f5412"
down_revision: Union[str, None] = "8940cfdef107"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.execute("ALTER TYPE emailprovider ADD VALUE 'OUTLOOK'")
    op.add_column("users", sa.Column("outlook_id", sa.String(), nullable=True))
    op.create_unique_constraint("unique_google_id", "users", ["google_id"])
    op.create_unique_constraint("unique_outlook_id", "users", ["outlook_id"])
    op.create_unique_constraint(None, "users", ["outlook_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, "users", type_="unique")
    op.drop_constraint("unique_outlook_id", "users", type_="unique")
    op.drop_constraint("unique_google_id", "users", type_="unique")
    op.drop_column("users", "outlook_id")
    op.execute("ALTER TYPE emailprovider DROP VALUE 'OUTLOOK'")
    # ### end Alembic commands ###
