"""Add email account settings

Revision ID: b30cf2890068
Revises: 52d4f3f2d559
Create Date: 2025-05-10 21:12:58.305999

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b30cf2890068"
down_revision: Union[str, None] = "52d4f3f2d559"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "settings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email_account_id", sa.UUID(), nullable=True),
        sa.Column("email_list", sa.JSON(), nullable=True),
        sa.Column("email_preferences", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["email_account_id"],
            ["email_accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("settings")
    # ### end Alembic commands ###
