import os

from dotenv import load_dotenv

load_dotenv()

GOOGLE_CLIENT_CONFIG = os.getenv("GOOGLE_CLIENT_CONFIG")
GOOGLE_CLIENT_ID = eval(GOOGLE_CLIENT_CONFIG)["web"]["client_id"]
GOOGLE_CLIENT_SECRET = eval(GOOGLE_CLIENT_CONFIG)["web"]["client_secret"]
GOOGLE_REDIRECT_URI = os.getenv("GOOGLE_REDIRECT_URI")
SECRET_KEY = os.getenv("SECRET_KEY")
POSTGRES_URL = os.getenv("POSTGRES_URL")
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND")
STAGE = os.getenv("STAGE")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
PINECONE_API_KEY = os.getenv("PINECONE_API_KEY")
XAI_API_KEY = os.getenv("XAI_API_KEY")
MSFT_TENANT_ID = os.getenv("MSFT_TENANT_ID")
MSFT_CLIENT_ID = os.getenv("MSFT_CLIENT_ID")
MSFT_CLIENT_SECRET = os.getenv("MSFT_CLIENT_SECRET")
MSFT_REDIRECT_URI = os.getenv("MSFT_REDIRECT_URI")
STRIPE_PUBLISHABLE_KEY = os.getenv("STRIPE_PUBLISHABLE_KEY")
STRIPE_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY")
GCP_BUCKET_NAME = os.getenv("GCP_BUCKET_NAME")
DISCORD_USER_ALERTS_CHANNEL = os.getenv("DISCORD_USER_ALERTS_CHANNEL")
GCP_BUCKET_CREDENTIALS = os.getenv("GCP_BUCKET_CREDENTIALS")
TELNYX_API_KEY = os.getenv("TELNYX_API_KEY")
TELNYX_SECRET_KEY = os.getenv("TELNYX_SECRET_KEY")
PHONE_NUMBER_NOT_FOUND_MESSAGE = os.getenv("PHONE_NUMBER_NOT_FOUND_MESSAGE")
