name: Push to Artifact Registry

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: dash-ai-app
  REGION: us-central1
  REPO_NAME: web
  TAG: latest

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up gcloud CLI
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true
      
      - name: Set dynamic image name
        run: |
          echo "IMAGE_NAME=${{ github.sha }}" >> $GITHUB_ENV
          echo "FASTAPI_IMAGE=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ github.sha }}:${{ env.TAG }}" >> $GITHUB_ENV

      - name: Authenticate Docker for Artifact Registry
        run: |
          gcloud auth configure-docker $REGION-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker build -t $FASTAPI_IMAGE .

      - name: Push Docker image
        run: |
          docker push $FASTAPI_IMAGE

